services:
  node0:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: dekvs-node0
    hostname: node0
    ports:
      - "8080:8080"
      - "9090:9090"
    command: >
      --id=node0
      --raft-bind-addr=0.0.0.0:9090
      --raft-adv-addr=node0:9090
      --grpc-port=8080
      --join=false
      --enable-metrics=true
      --metrics-port=19090
    networks:
      - dekvs-network
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "-max-time", "5", "localhost:8080", "kv.KVService/Get"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  node1:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: dekvs-node1
    hostname: node1
    ports:
      - "8081:8080"
      - "9091:9090"
    command: >
      --id=node1
      --raft-bind-addr=0.0.0.0:9090
      --raft-adv-addr=node1:9090
      --grpc-port=8080
      --join=true
      --leader-addrs=node0:8080
      --enable-metrics=true
      --metrics-port=19090
    networks:
      - dekvs-network
    depends_on:
      node0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "-max-time", "5", "localhost:8080", "kv.KVService/Get"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  node2:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: dekvs-node2
    hostname: node2
    ports:
      - "8082:8080"
      - "9092:9090"
    command: >
      --id=node2
      --raft-bind-addr=0.0.0.0:9090
      --raft-adv-addr=node2:9090
      --grpc-port=8080
      --join=true
      --leader-addrs=node0:8080
      --enable-metrics=true
      --metrics-port=19090
    networks:
      - dekvs-network
    depends_on:
      node0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "-max-time", "5", "localhost:8080", "kv.KVService/Get"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: dekvs-prometheus
    ports:
      - "30090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - dekvs-network
    depends_on:
      - node0
      - node1
      - node2
    restart: unless-stopped

networks:
  dekvs-network:
    driver: bridge
