global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'dekvs'
    static_configs:
      - targets: ['node0:19090', 'node1:19090', 'node2:19090', 'node3:19090']
        labels:
          group: 'dekvs-cluster'
